// Copyright 2026 nader-helmy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type ByContextListResponse struct {
	ContextId string          `json:"context_id"`
	Entries   json.RawMessage `json:"entries"`
}

type ByCreatorListResponse struct {
	CreatorKey string          `json:"creator_key"`
	Entries    json.RawMessage `json:"entries"`
}

type EntriesPostEntryResponse struct {
	Index      int    `json:"index"`
	RecordHash string `json:"record_hash"`
}

type Entry struct {
	ContextId     string `json:"context_id"`
	CreatorKey    string `json:"creator_key"`
	EventType     string `json:"event_type"`
	EventTypeByte int    `json:"event_type_byte"`
	Index         int    `json:"index"`
	RecordHash    string `json:"record_hash"`
	TimestampMs   int    `json:"timestamp_ms"`
}

type EntrySubmission struct {
	Signature     string `json:"signature"`
	SignedPayload string `json:"signed_payload"`
}

type RecentListResponse struct {
	Entries  json.RawMessage `json:"entries"`
	Offset   int             `json:"offset"`
	Returned int             `json:"returned"`
	TreeSize int             `json:"tree_size"`
}

type StatsGetResponse struct {
	DistinctSigners    int             `json:"distinct_signers"`
	EntriesByEventType json.RawMessage `json:"entries_by_event_type"`
	NewestTimestampMs  int             `json:"newest_timestamp_ms"`
	OldestTimestampMs  int             `json:"oldest_timestamp_ms"`
	TreeSize           int             `json:"tree_size"`
}
