// Copyright 2026 nader-helmy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"atrib-log-pp-cli/internal/cli"
	"atrib-log-pp-cli/internal/client"
	"atrib-log-pp-cli/internal/config"
	"atrib-log-pp-cli/internal/mcp/cobratree"
	"atrib-log-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("by-context_list",
			mcplib.WithDescription("All entries in a context (session). Required: hex. Optional: limit (default: 50). Returns the ByContextListResponse."),
			mcplib.WithString("hex", mcplib.Required(), mcplib.Description("32-char hex context_id")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/by-context/{hex}", false, []mcpParamBinding{{PublicName: "hex", WireName: "hex", Location: "path"}, {PublicName: "limit", WireName: "limit", Location: "query"}}, []string{"hex"}),
	)
	s.AddTool(
		mcplib.NewTool("by-creator_list",
			mcplib.WithDescription("All entries by signer (creator key). Required: key. Optional: limit (default: 50). Returns the ByCreatorListResponse."),
			mcplib.WithString("key", mcplib.Required(), mcplib.Description("Base64url-encoded Ed25519 public key")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/by-creator/{key}", false, []mcpParamBinding{{PublicName: "key", WireName: "key", Location: "path"}, {PublicName: "limit", WireName: "limit", Location: "query"}}, []string{"key"}),
	)
	s.AddTool(
		mcplib.NewTool("checkpoint_get",
			mcplib.WithDescription("Returns the current signed checkpoint (tree size + root hash + log signature). Use this to anchor your local view of the log and verify inclusion proofs."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/checkpoint", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("entries_post-entry",
			mcplib.WithDescription("Write path. Submit a signed record for inclusion in the log. Returns a fresh inclusion-proof bundle on success. Required: chain_root, content_id, context_id, creator_key, event_type, signature, spec_version, timestamp. Optional: args_hash, provenance_token, result_hash, session_token, tool_name."),
			mcplib.WithString("args_hash", mcplib.Description("Args hash")),
			mcplib.WithString("chain_root", mcplib.Required(), mcplib.Description("Chain root")),
			mcplib.WithString("content_id", mcplib.Required(), mcplib.Description("Content id")),
			mcplib.WithString("context_id", mcplib.Required(), mcplib.Description("Context id")),
			mcplib.WithString("creator_key", mcplib.Required(), mcplib.Description("base64url-encoded Ed25519 public key")),
			mcplib.WithString("event_type", mcplib.Required(), mcplib.Description("Event type")),
			mcplib.WithString("provenance_token", mcplib.Description("Provenance token")),
			mcplib.WithString("result_hash", mcplib.Description("Result hash")),
			mcplib.WithString("session_token", mcplib.Description("Session token")),
			mcplib.WithString("signature", mcplib.Required(), mcplib.Description("Ed25519 signature, base64url")),
			mcplib.WithString("spec_version", mcplib.Required(), mcplib.Description("Spec version")),
			mcplib.WithNumber("timestamp", mcplib.Required(), mcplib.Description("Timestamp")),
			mcplib.WithString("tool_name", mcplib.Description("Tool name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1/entries", false, []mcpParamBinding{{PublicName: "args_hash", WireName: "args_hash", Location: "body"}, {PublicName: "chain_root", WireName: "chain_root", Location: "body"}, {PublicName: "content_id", WireName: "content_id", Location: "body"}, {PublicName: "context_id", WireName: "context_id", Location: "body"}, {PublicName: "creator_key", WireName: "creator_key", Location: "body"}, {PublicName: "event_type", WireName: "event_type", Location: "body"}, {PublicName: "provenance_token", WireName: "provenance_token", Location: "body"}, {PublicName: "result_hash", WireName: "result_hash", Location: "body"}, {PublicName: "session_token", WireName: "session_token", Location: "body"}, {PublicName: "signature", WireName: "signature", Location: "body"}, {PublicName: "spec_version", WireName: "spec_version", Location: "body"}, {PublicName: "timestamp", WireName: "timestamp", Location: "body"}, {PublicName: "tool_name", WireName: "tool_name", Location: "body"}}, []string{}),
	)
	// PATCH: expose log-node endpoints added after the original generated MCP
	// surface. Keep stream out of MCP because it is an infinite SSE response.
	s.AddTool(
		mcplib.NewTool("feed-json_get-json-feed",
			mcplib.WithDescription("JSON Feed 1.1 companion for consumers that cannot hold a long-lived Server-Sent Events connection. Optional: creator_key, context_id, event_type, since, limit, offset."),
			mcplib.WithString("creator_key", mcplib.Description("Creator key")),
			mcplib.WithString("context_id", mcplib.Description("Context id")),
			mcplib.WithString("event_type", mcplib.Description("Event type")),
			mcplib.WithString("since", mcplib.Description("Since")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithNumber("offset", mcplib.Description("Offset")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/feed.json", false, []mcpParamBinding{{PublicName: "creator_key", WireName: "creator_key", Location: "query"}, {PublicName: "context_id", WireName: "context_id", Location: "query"}, {PublicName: "event_type", WireName: "event_type", Location: "query"}, {PublicName: "since", WireName: "since", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("log-pubkey_get",
			mcplib.WithDescription("Get the log public key in C2SP signed-note vkey format."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/log-pubkey", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("lookup_by-hash",
			mcplib.WithDescription("Lookup entry by record hash. Required: hex. Returns the Entry."),
			mcplib.WithString("hex", mcplib.Required(), mcplib.Description("SHA-256 hex (no `sha256:` prefix)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/lookup/{hex}", false, []mcpParamBinding{{PublicName: "hex", WireName: "hex", Location: "path"}}, []string{"hex"}),
	)
	s.AddTool(
		mcplib.NewTool("proof_get-by-hash",
			mcplib.WithDescription("Recover an inclusion-proof bundle for a record that is already included in the log. Required: hex."),
			mcplib.WithString("hex", mcplib.Required(), mcplib.Description("SHA-256 hex (no `sha256:` prefix)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/proof/{hex}", false, []mcpParamBinding{{PublicName: "hex", WireName: "hex", Location: "path"}}, []string{"hex"}),
	)
	s.AddTool(
		mcplib.NewTool("pubkey_get",
			mcplib.WithDescription("Get verification public key."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/pubkey", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("recent_list",
			mcplib.WithDescription("Most recent entries. Optional: limit (default: 10), offset (default: 0). Returns the RecentListResponse."),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithNumber("offset", mcplib.Description("Offset")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/recent", false, []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("stats_get",
			mcplib.WithDescription("Tree statistics. Returns the StatsGetResponse."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/stats", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tile_get",
			mcplib.WithDescription("Sigsum-style Merkle tile at level L, position N. Required: level, n."),
			mcplib.WithNumber("level", mcplib.Required(), mcplib.Description("Level")),
			mcplib.WithNumber("n", mcplib.Required(), mcplib.Description("N")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/tile/{level}/{n}", true, []mcpParamBinding{{PublicName: "level", WireName: "level", Location: "path"}, {PublicName: "n", WireName: "n", Location: "path"}}, []string{"level", "n"}),
	)
	s.AddTool(
		mcplib.NewTool("tile_get-entries",
			mcplib.WithDescription("Get entries within a tile (leaf-level). Required: n. Returns array of Entry."),
			mcplib.WithNumber("n", mcplib.Required(), mcplib.Description("N")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/tile/entries/{n}", false, []mcpParamBinding{{PublicName: "n", WireName: "n", Location: "path"}}, []string{"n"}),
	)
	// Search tool - faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool - ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool - front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror - exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if binaryResponse {
			headers = map[string]string{client.BinaryResponseHeader: "true"}
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if binaryResponse {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if binaryResponse {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if binaryResponse {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if binaryResponse {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if binaryResponse {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'atrib-log-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'atrib-log-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "atrib-log-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "atrib-log-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" - TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "atrib-log",
		"description": "atrib transparency log - Sigsum-style append-only Merkle log of signed agent action records. Each entry is a...",
		"archetype":   "generic",
		"tool_count":  13,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion atrib-log-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name":        "by-context",
				"description": "Manage by context",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "by-creator",
				"description": "Manage by creator",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "checkpoint",
				"description": "Manage checkpoint",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "entries",
				"description": "Manage entries",
				"endpoints":   []string{"post-entry"},
				"searchable":  true,
			},
			{
				"name":        "feed-json",
				"description": "Manage feed json",
				"endpoints":   []string{"get-json-feed"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "log-pubkey",
				"description": "Manage log pubkey",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "lookup",
				"description": "Manage lookup",
				"endpoints":   []string{"by-hash"},
				"searchable":  true,
			},
			{
				"name":        "proof",
				"description": "Manage proof",
				"endpoints":   []string{"get-by-hash"},
				"searchable":  true,
			},
			{
				"name":        "pubkey",
				"description": "Manage pubkey",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "recent",
				"description": "Manage recent",
				"endpoints":   []string{"list"},
				"syncable":    true,
			},
			{
				"name":        "stats",
				"description": "Manage stats",
				"endpoints":   []string{"get"},
				"syncable":    true,
			},
			{
				"name":        "tile",
				"description": "Manage tile",
				"endpoints":   []string{"get", "get-entries"},
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass offset parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
