// Copyright 2026 nader-helmy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

func newAPICmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "api [interface]",
		Short:       "Browse all API endpoints by interface name",
		Annotations: map[string]string{"mcp:read-only": "true"},
		Long: `Browse and call any API endpoint using the raw interface names.

The friendly top-level commands cover the most common operations.
This command provides access to ALL endpoints for power users and
agents that need full API coverage.

Run 'api' with no arguments to list all interfaces.
Run 'api <interface>' to see that interface's methods.`,
		Example: `  # List all available interfaces
  atrib-log-pp-cli api

  # Show methods for a specific interface
  atrib-log-pp-cli api <interface-name>`,
		RunE: func(cmd *cobra.Command, args []string) error {
			root := cmd.Root()

			if len(args) > 0 {
				target := strings.ToLower(args[0])
				// PATCH: promoted endpoint commands are not hidden interface
				// parents, so collect by pp:endpoint annotation instead.
				methods, short := collectAPIMethods(root, target)
				if len(methods) > 0 {
					if flags.asJSON {
						methodList := make([]map[string]any, 0, len(methods))
						for _, method := range methods {
							methodList = append(methodList, map[string]any{
								"name":    method.Name,
								"short":   method.Short,
								"command": method.Command,
							})
						}
						return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
							"interface": target,
							"short":     short,
							"methods":   methodList,
						}, flags)
					}
					fmt.Fprintf(cmd.OutOrStdout(), "%s - %s\n\nMethods:\n", target, short)
					for _, method := range methods {
						fmt.Fprintf(cmd.OutOrStdout(), "  %-50s %s\n", method.Command, method.Short)
					}
					fmt.Fprintf(cmd.OutOrStdout(), "\nUse '%s <command> --help' for details.\n", root.Name())
					return nil
				}
				return fmt.Errorf("interface %q not found. Run '%s-pp-cli api' to list all interfaces", args[0], "atrib-log")
			}

			// PATCH: include promoted one-shot endpoint commands in addition
			// to hidden resource parents like tile.
			ifaces := collectAPIInterfaces(root)

			// JSON envelope: {interfaces: [...], note?: "..."}.
			if flags.asJSON {
				out := map[string]any{"interfaces": ifaces}
				if len(ifaces) == 0 {
					out["interfaces"] = []apiInterfaceEntry{}
					out["note"] = "No API interfaces found."
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if len(ifaces) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "No API interfaces found.")
				return nil
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Available API interfaces (%d):\n\n", len(ifaces))
			for _, e := range ifaces {
				fmt.Fprintf(cmd.OutOrStdout(), "  %-45s %s\n", e.Name, e.Short)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "\nUse '%s-pp-cli api <interface>' to see methods.\n", "atrib-log")
			return nil
		},
	}

	return cmd
}

type apiInterfaceEntry struct {
	Name  string `json:"name"`
	Short string `json:"short"`
}

type apiMethodEntry struct {
	Name    string
	Short   string
	Command string
}

func collectAPIInterfaces(root *cobra.Command) []apiInterfaceEntry {
	byName := map[string]apiInterfaceEntry{}
	walkAPICommands(root, func(cmd *cobra.Command) {
		endpoint := cmd.Annotations["pp:endpoint"]
		if endpoint == "" {
			return
		}
		name := apiInterfaceName(endpoint)
		if name == "" {
			return
		}
		short := cmd.Short
		if cmd.Parent() != nil && cmd.Parent().Hidden && cmd.Parent().Name() == name {
			short = cmd.Parent().Short
		}
		if _, exists := byName[name]; !exists {
			byName[name] = apiInterfaceEntry{Name: name, Short: short}
		}
	})
	out := make([]apiInterfaceEntry, 0, len(byName))
	for _, e := range byName {
		out = append(out, e)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func collectAPIMethods(root *cobra.Command, target string) ([]apiMethodEntry, string) {
	var methods []apiMethodEntry
	short := ""
	walkAPICommands(root, func(cmd *cobra.Command) {
		endpoint := cmd.Annotations["pp:endpoint"]
		if apiInterfaceName(endpoint) != target {
			return
		}
		methodName := endpoint
		if dot := strings.Index(endpoint, "."); dot >= 0 && dot < len(endpoint)-1 {
			methodName = endpoint[dot+1:]
		}
		if short == "" {
			short = cmd.Short
			if cmd.Parent() != nil && cmd.Parent().Hidden && cmd.Parent().Name() == target {
				short = cmd.Parent().Short
			}
		}
		methods = append(methods, apiMethodEntry{
			Name:    methodName,
			Short:   cmd.Short,
			Command: strings.TrimPrefix(cmd.CommandPath(), root.Name()+" "),
		})
	})
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })
	return methods, short
}

func apiInterfaceName(endpoint string) string {
	if endpoint == "" {
		return ""
	}
	if dot := strings.Index(endpoint, "."); dot >= 0 {
		return endpoint[:dot]
	}
	return endpoint
}

func walkAPICommands(cmd *cobra.Command, visit func(*cobra.Command)) {
	for _, child := range cmd.Commands() {
		visit(child)
		walkAPICommands(child, visit)
	}
}
