// Copyright 2026 nader-helmy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"

	"github.com/spf13/cobra"
)

func newStreamPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagCreatorKey string
	var flagContextId string
	var flagEventType string
	var flagSince string

	cmd := &cobra.Command{
		Use:     "stream",
		Short:   "Stream new log entries as Server-Sent Events",
		Long:    "Opens /v1/stream and writes raw Server-Sent Events lines to stdout until the connection closes.",
		Example: "  atrib-log-pp-cli stream --event-type tool_call",
		Annotations: map[string]string{
			"mcp:hidden":  "true",
			"pp:endpoint": "stream.log-entries",
			"pp:method":   "GET",
			"pp:path":     "/v1/stream",
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("stream emits raw Server-Sent Events; do not combine it with structured output flags")
			}
			if cmd.Flags().Changed("event-type") {
				allowedEventType := []string{"tool_call", "observation", "annotation", "revision", "transaction", "directory_anchor", "extension", "reserved"}
				validEventType := false
				for _, v := range allowedEventType {
					if flagEventType == v {
						validEventType = true
						break
					}
				}
				if !validEventType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "event-type", flagEventType, allowedEventType)
				}
			}

			c, err := flags.newClient()
			if err != nil {
				return err
			}
			// PATCH: SSE is an infinite response, so the one-shot generated
			// client reader would block until timeout. Stream lines directly.
			if !cmd.Root().PersistentFlags().Changed("timeout") {
				c.HTTPClient.Timeout = 0
			}

			u, err := url.Parse(c.BaseURL + "/v1/stream")
			if err != nil {
				return err
			}
			q := u.Query()
			if flagCreatorKey != "" {
				q.Set("creator_key", flagCreatorKey)
			}
			if flagContextId != "" {
				q.Set("context_id", flagContextId)
			}
			if flagEventType != "" {
				q.Set("event_type", flagEventType)
			}
			if flagSince != "" {
				q.Set("since", flagSince)
			}
			u.RawQuery = q.Encode()

			req, err := http.NewRequestWithContext(cmd.Context(), http.MethodGet, u.String(), nil)
			if err != nil {
				return err
			}
			req.Header.Set("Accept", "text/event-stream")
			req.Header.Set("User-Agent", "atrib-log-pp-cli/stream")
			if c.Config != nil {
				for k, v := range c.Config.Headers {
					req.Header.Set(k, v)
				}
				if auth := c.Config.AuthHeader(); auth != "" {
					req.Header.Set("Authorization", auth)
				}
			}

			resp, err := c.HTTPClient.Do(req)
			if err != nil {
				return err
			}
			defer resp.Body.Close()
			if resp.StatusCode >= 400 {
				body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
				return classifyAPIError(&apiStatusError{method: http.MethodGet, path: "/v1/stream", status: resp.StatusCode, body: string(body)}, flags)
			}

			scanner := bufio.NewScanner(resp.Body)
			scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
			for scanner.Scan() {
				fmt.Fprintln(cmd.OutOrStdout(), scanner.Text())
			}
			return scanner.Err()
		},
	}
	cmd.Flags().StringVar(&flagCreatorKey, "creator-key", "", "Creator key")
	cmd.Flags().StringVar(&flagContextId, "context-id", "", "Context id")
	cmd.Flags().StringVar(&flagEventType, "event-type", "", "Event type (one of: tool_call, observation, annotation, revision, transaction, directory_anchor, extension, reserved)")
	cmd.Flags().StringVar(&flagSince, "since", "", "Since timestamp in milliseconds or ISO 8601 form")

	return cmd
}

type apiStatusError struct {
	method string
	path   string
	status int
	body   string
}

func (e *apiStatusError) Error() string {
	return fmt.Sprintf("%s %s returned HTTP %d: %s", e.method, e.path, e.status, e.body)
}

func (e *apiStatusError) StatusCode() int {
	return e.status
}
