// Copyright 2026 nader-helmy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEntriesPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyArgsHash string
	var bodyChainRoot string
	var bodyContentId string
	var bodyContextId string
	var bodyCreatorKey string
	var bodyEventType string
	var bodyInformedBy string
	var bodyProvenanceToken string
	var bodyResultHash string
	var bodySessionToken string
	var bodySignature string
	var bodySpecVersion string
	var bodyTimestamp int
	var bodyToolName string

	cmd := &cobra.Command{
		Use:         "entries",
		Short:       "Write path. Submit a signed record for inclusion in the log. Returns a fresh inclusion-proof bundle on success.",
		Long:        "Shortcut for 'entries post-entry'. Write path. Submit a signed record for inclusion in the log. Returns a fresh inclusion-proof bundle on success.",
		Example:     "  atrib-log-pp-cli entries --chain-root example-value",
		Annotations: map[string]string{"pp:endpoint": "entries.post-entry", "pp:method": "POST", "pp:path": "/v1/entries"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("chain-root") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "chain-root")
			}
			if !cmd.Flags().Changed("content-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "content-id")
			}
			if !cmd.Flags().Changed("context-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "context-id")
			}
			if !cmd.Flags().Changed("creator-key") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "creator-key")
			}
			if !cmd.Flags().Changed("event-type") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "event-type")
			}
			if !cmd.Flags().Changed("signature") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "signature")
			}
			if !cmd.Flags().Changed("spec-version") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "spec-version")
			}
			if !cmd.Flags().Changed("timestamp") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "timestamp")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/entries"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyArgsHash != "" {
				body["args_hash"] = bodyArgsHash
			}
			if bodyChainRoot != "" {
				body["chain_root"] = bodyChainRoot
			}
			if bodyContentId != "" {
				body["content_id"] = bodyContentId
			}
			if bodyContextId != "" {
				body["context_id"] = bodyContextId
			}
			if bodyCreatorKey != "" {
				body["creator_key"] = bodyCreatorKey
			}
			if bodyEventType != "" {
				body["event_type"] = bodyEventType
			}
			if bodyInformedBy != "" {
				var parsedInformedBy any
				if err := json.Unmarshal([]byte(bodyInformedBy), &parsedInformedBy); err != nil {
					return fmt.Errorf("parsing --informed-by JSON: %w", err)
				}
				body["informed_by"] = parsedInformedBy
			}
			if bodyProvenanceToken != "" {
				body["provenance_token"] = bodyProvenanceToken
			}
			if bodyResultHash != "" {
				body["result_hash"] = bodyResultHash
			}
			if bodySessionToken != "" {
				body["session_token"] = bodySessionToken
			}
			if bodySignature != "" {
				body["signature"] = bodySignature
			}
			if bodySpecVersion != "" {
				body["spec_version"] = bodySpecVersion
			}
			if bodyTimestamp != 0 {
				body["timestamp"] = bodyTimestamp
			}
			if bodyToolName != "" {
				body["tool_name"] = bodyToolName
			}
			data, _, err := c.PostWithParams(path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyArgsHash, "args-hash", "", "Args hash")
	cmd.Flags().StringVar(&bodyChainRoot, "chain-root", "", "Chain root")
	cmd.Flags().StringVar(&bodyContentId, "content-id", "", "Content id")
	cmd.Flags().StringVar(&bodyContextId, "context-id", "", "Context id")
	cmd.Flags().StringVar(&bodyCreatorKey, "creator-key", "", "base64url-encoded Ed25519 public key")
	cmd.Flags().StringVar(&bodyEventType, "event-type", "", "Event type")
	cmd.Flags().StringVar(&bodyInformedBy, "informed-by", "", "Informed by")
	cmd.Flags().StringVar(&bodyProvenanceToken, "provenance-token", "", "Provenance token")
	cmd.Flags().StringVar(&bodyResultHash, "result-hash", "", "Result hash")
	cmd.Flags().StringVar(&bodySessionToken, "session-token", "", "Session token")
	cmd.Flags().StringVar(&bodySignature, "signature", "", "Ed25519 signature, base64url")
	cmd.Flags().StringVar(&bodySpecVersion, "spec-version", "", "Spec version")
	cmd.Flags().IntVar(&bodyTimestamp, "timestamp", 0, "Timestamp")
	cmd.Flags().StringVar(&bodyToolName, "tool-name", "", "Tool name")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
