// Copyright 2026 nader-helmy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFeedJsonPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagCreatorKey string
	var flagContextId string
	var flagEventType string
	var flagSince string
	var flagLimit int
	var flagOffset string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "feed-json",
		Short:       "JSON Feed 1.1 companion for consumers that cannot hold a long-lived Server-Sent Events connection. Items are...",
		Long:        "Shortcut for 'feed-json get-json-feed'. JSON Feed 1.1 companion for consumers that cannot hold a long-lived Server-Sent Events connection. Items are...",
		Example:     "  atrib-log-pp-cli feed-json",
		Annotations: map[string]string{"pp:endpoint": "feed-json.get-json-feed", "pp:method": "GET", "pp:path": "/v1/feed.json", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("event-type") {
				allowedEventType := []string{"tool_call", "observation", "annotation", "revision", "transaction", "directory_anchor", "extension", "reserved"}
				validEventType := false
				for _, v := range allowedEventType {
					if flagEventType == v {
						validEventType = true
						break
					}
				}
				if !validEventType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "event-type", flagEventType, allowedEventType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/feed.json"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "feed-json", path, map[string]string{
				"creator_key": fmt.Sprintf("%v", flagCreatorKey),
				"context_id":  fmt.Sprintf("%v", flagContextId),
				"event_type":  fmt.Sprintf("%v", flagEventType),
				"since":       fmt.Sprintf("%v", flagSince),
				"limit":       fmt.Sprintf("%v", flagLimit),
				"offset":      fmt.Sprintf("%v", flagOffset),
			}, nil, flagAll, "offset", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagCreatorKey, "creator-key", "", "Creator key")
	cmd.Flags().StringVar(&flagContextId, "context-id", "", "Context id")
	cmd.Flags().StringVar(&flagEventType, "event-type", "", "Event type (one of: tool_call, observation, annotation, revision, transaction, directory_anchor, extension, reserved)")
	cmd.Flags().StringVar(&flagSince, "since", "", "Since")
	cmd.Flags().IntVar(&flagLimit, "limit", 20, "Limit")
	cmd.Flags().StringVar(&flagOffset, "offset", "0", "Offset")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
