// Copyright 2026 nader-helmy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTileGetCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "get <level> <n>",
		Short:       "Sigsum-style Merkle tile at level L, position N",
		Example:     "  atrib-log-pp-cli tile get 42 42",
		Annotations: map[string]string{"pp:endpoint": "tile.get", "pp:method": "GET", "pp:path": "/v1/tile/{level}/{n}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/tile/{level}/{n}"
			path = replacePathParam(path, "level", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("n is required\nUsage: %s <%s>", cmd.CommandPath(), "n"))
			}
			path = replacePathParam(path, "n", args[1])
			headerOverrides := map[string]string{
				"X-Printing-Press-Binary-Response": "true",
			}
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "tile", false, path, params, headerOverrides)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			_ = json.Valid
			_ = os.Stderr
			_ = prov
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}

	return cmd
}
