// Copyright 2026 nader-helmy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTileCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "tile",
		Short:  "Manage tile",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTileGetCmd(flags))
	cmd.AddCommand(newTileGetEntriesCmd(flags))
	return cmd
}
